team_libra/example/urls.py
from django.urls import path
from .class_views import *

app_name  = 'example'

urlpatterns = [
    #EJEMPLO DE URL 
    path('', Example.as_view(), name='Docente'),

    path('CREAR_USUARIO/', Crear_usuario.as_view(), name='example'),

    path('Materia/', Materias.as_view(), name='Materias'),

]

#     EJEMPLO MAS EXPLICADO .I.
#     path('NOMBRE DE LA URL QUE QUIERAS' , <---- NO OLVIDAR LAS COMAS 
#     NOMBRE DE LA CLASE QUE HICISTE.as_view() , 
#     name='NOMBRE PARA IDENTIFICAR ESTA URL EN ALGUNA FUNCION O CLASE')

team_libra/team_libra/urls.py
from example import class_views

"""team_libra URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls')),
    path('materias/', class_views.Materias.as_view(), name='Materias'),
]

team_libra/example/models.py
from django.db import models

# Create your models here.

team_libra/example/views.py
from django.shortcuts import render

# Create your views here.

team_libra/templates/cuenta.html
{{ cesun_api_crear_usuario }}

team_libra/templates/example.html
{% extends 'main.html' %}

{% block content %}
<div class="container" style="padding-top:10px">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Docente ID</th>
          <th scope="col">Nombre</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        {% for docente in cesun_api %}
        <tr>
          <th scope="row">{{ docente.id_docente }}</th>
          <td>{{ docente.nombre_docente }}</td>
          <td>{{ docente.correo_Personal }}</td>
        </tr>
        {% endfor %}
      </tbody>
</div>

{% endblock content %}

team_libra/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="./main.html">
  <link rel="icon" type="image/png" href="{% static  'Main/CESUNE.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    COORDINACION-CESUN
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static  'Main/assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static  'Main/assets/demo/demo.css' %}" rel="stylesheet" />

  <!--ARCHIVO PARA AJUSTES -->

  <link rel="stylesheet" type="text/css" href="{% static  'Main/ajustes.css' %}" rel="stylesheet" />

</head>

<body class="">
  <div class="wrapper ">

    <div class="sidebar" data-color="cesun" data-background-color="white" data-image="{% static  'Main/assets/img/sidebar-1.jpg' %}">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="orange | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
    <div class="logo">
        <a href="" class="simple-text logo-normal">
        <img src="{% static  'Main/cesunnnn.png' %}" alt="">
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item active">
               <a class="nav-link" href="{% url 'example:Docente' %}">
                 <i class="material-icons">account_box</i>
                 <p>DOCENTES</p>
               </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'example:Materias' %}">
                <i class="material-icons">contacts</i>
                <p>MATERIAS</p>
              </a>
            </li>
          <!----<li class="nav-item active">
            <a class="nav-link" href="">
              <i class="material-icons">dynamic_feed</i>
              <p>Materias</p>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="">
              <i class="material-icons">contacts</i>
              <p>DOCENTES</p>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="">
              <i class="material-icons">school</i>
              <p>UNIVERSIDAD</p>
            </a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="">
                <i class="material-icons">insert_chart_outlined</i>
                <p>Crear Nivel de Estudio</p>
              </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="">
              <i class="material-icons">contact_phone</i>
              <p>Dar de baja a un docente</p>

            </a>
         </li>---->
        </ul>
      </div>
    </div>

    <div class="main-panel" >
          <!--<div class="content" >-->
              {% block content %}
              <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <img src="{% static 'Main/maxresdefault.jpg' %}" alt="" style="width: 155%;">
                    </div>
                  </div>
                </div>
              </div>
              {% endblock content %}
          <!--</div>-->
    </div>
  </div>

</body>

team_libra/templates/materias.html
{% extends 'main.html' %}

{% block content %}

<div class="container" style="padding-top:10px">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Materia</th>
          <th scope="col">Carrera</th>
        </tr>
      </thead>
      <tbody>
        {% for docente in cesun_api_Materias %}
        <tr>
          <th scope="row">{{ docente.id_materia }}</th>
          <td>{{ docente.nombre }}</td>
          <td>{{ docente.carrera }}</td>
        </tr>
        {% endfor %}
      </tbody>
</div>
{% endblock content %}